FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Install dependencies
COPY backend/requirements.txt .

RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY backend ./code

# Default command for celery worker
CMD ["celery", "-A", "app.celery_app", "worker"]
